### ISSUE TITLE
 could not find `wemod-pro-unlocker` in registry `crates-io` with version `*`

### ISSUE THREAD

**Issue by imedjendoubi** [DaBaival/wemod-pro-unlocker#13]
I get this error after trying to install cargo install wemod-pro-unlocker

**Comment by lonewolf0708** [comment]
It's not compatible with the latest WeMod build (9.x.x) but you can download a pre-cracked wemod 8.2.0 and extract it anywhere from https://github.com/DaBaival/wemod-pro-unlocker/releases/tag/Patched

**Comment by DaBaival** [comment]
已上传wemod v9.0.3 Patched版本的文件
https://github.com/DaBaival/wemod-pro-unlocker/releases/tag/Patched
