### ISSUE TITLE
地图传送功能用不了

### ISSUE THREAD

**Issue by 756066377** [DaBaival/wemod-pro-unlocker#19]
![屏幕截图 2024-06-21 122650](https://github.com/DaBaival/wemod-pro-unlocker/assets/92951395/e04a4a72-ebdd-4642-8c75-d8b8775f483e)

**Comment by DaBaival** [comment]
> ![屏幕截图 2024-06-21 122650](https://github.com/DaBaival/wemod-pro-unlocker/assets/92951395/e04a4a72-ebdd-4642-8c75-d8b8775f483e)
> 

仅解锁本地功能，要地图的话请充会员去。服务器验证的东西，除非你能把人家服务器黑了。
