### ISSUE TITLE
Can i get some with with building?

### ISSUE THREAD

**Issue by weitrem** [DaBaival/wemod-pro-unlocker#4]
Is this repo still up to date?

**Comment by DaBaival** [comment]
Yes, Wemod of 8.16.1 can still be used.
8.16.1 Because it should be the latest version.
Note that it is only applicable to wemod downloaded from official website and installed on drive C, and any version may not be available! ! !

**Comment by DaBaival** [comment]
是的，8.16.1仍然可以使用。8.16.1应该是wemod最新版本。注意，仅适用于从官网下载并安装在c盘的wemod，除此之外的版本都可能无法使用！！！
