### ISSUE TITLE
最新稳定版本已经更新到9.0.1了 已经不能使用了

### ISSUE THREAD

**Issue by lianyuxiuluo** [DaBaival/wemod-pro-unlocker#6]
最新稳定版本已经更新到9.0.1了 已经不能使用了
The latest stable version has been updated to 9.0.1 and is no longer available

**Comment by DaBaival** [comment]
wemod应用程序不更新，又不影响修改器更新，为什么非就得用最新版本？

**Comment by lianyuxiuluo** [comment]
> wemod应用程序不更新，又不影响修改器更新，为什么非就得用最新版本？

我馋WEMOD的功能又不是修改器 修改器都有平替的 部分甚至比WEMOD好使

**Comment by DaBaival** [comment]
> > wemod应用程序不更新，又不影响修改器更新，为什么非就得用最新版本？
> 
> 我馋WEMOD的功能又不是修改器 修改器都有平替的 部分甚至比WEMOD好使

主要是最新版的功能解锁后，跟之前的版本也没区别呀。地图的相关功能不是要开会员?

**Comment by DaBaival** [comment]
> 最新稳定版本已经更新到9.0.1了 已经不能使用了 The latest stable version has been updated to 9.0.1 and is no longer available

已上传wemod v9.0.3 Patched版本的文件
https://github.com/DaBaival/wemod-pro-unlocker/releases/tag/Patched
