### ISSUE TITLE
can you upload zip folder of old isntalled wemod mine doesnt open after patch

### ISSUE THREAD

**Issue by MrHacker38388** [DaBaival/wemod-pro-unlocker#8]
can you upload zip folder of old isntalled wemod you have mine doesnt open after patch

**Comment by DaBaival** [comment]
https://github.com/DaBaival/wemod-pro-unlocker/releases/tag/Patched

**Comment by MrHacker38388** [comment]
THANK YOU SO MUCH BRO MAY GOD BLESS YOU AND GIVE YOU HAPPNIESS THE FUCKING TIME LIMIT IS REMOVED LETS GO
